# Generated by Django 5.1.2 on 2024-10-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('career_goal', models.TextField()),
                ('skills', models.TextField()),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=50)),
                ('industry_preference', models.CharField(max_length=100)),
            ],
        ),
    ]
